# Generated by Django 5.2 on 2025-06-14 11:30

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookinguser_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinguser',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookinguser',
            name='user_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
