# Generated by Django 5.2 on 2025-06-14 11:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookinguser_user_name_bookinguser_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinguser',
            name='user_name',
            field=models.CharField(default='ali', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinguser',
            name='user_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+996323866', max_length=128, region=None),
        ),
    ]
